language: ruby
# only run CI-builds on master branch
branches:
  only:
  - master
rvm:
- 2.2.3
# set execution permission on our build script
before_script:
 - chmod +x ./script/cibuild
# path to our build script. 
# Travis will run `bundle install` by default before running our script
script: ./script/cibuild
exclude: [vendor]
sudo: false
addons:
  ssh_known_hosts: teambroncobots.com
before_deploy:
- openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/_dist broncobots_travis@teambroncobots.com:/home/broncobots_travis/qa.teambroncobots.com
  on:
    branch: gh-pages
